capstone_application/basic_app/urls.py
from django.urls import path
from . import views


app_name = "basic_app"

urlpatterns = [
	path('', views.index, name="home"),
	path('results/', views.results, name='results'),
    path('info/', views.info, name='info'),
    path('about/', views.about, name='about'),
	]


    

capstone_application/capstone_application/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from basic_app import views

urlpatterns = [
    path('', include('basic_app.urls', namespace="basic_app")),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

capstone_application/basic_app/models.py
from django.db import models
from django.core.files.base import File
import os
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.
class ImageInfo(models.Model):

    # Create relationship (don't inherit from User!)

    # Add any additional attributes you want
    image_name = models.CharField(max_length=256)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    image = models.ImageField(upload_to= 'images/')
    cc_image = models.ImageField(blank=True, null=True)
    result = models.FileField(blank=True, null=True, upload_to='final/')

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.image_name

    def update_result(self, new_path):
        self.result.save(os.path.basename(new_path), File(open(new_path, "wb+")), save=True)

capstone_application/basic_app/forms.py
from socket import fromshare
from django import forms
from .models import ImageInfo

class ImageInfoForm(forms.ModelForm):
    class Meta():
        model = ImageInfo
        fields = ('image_name', 'image')
        widgets = {
            'image_name': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

capstone_application/basic_app/views.py
from importlib.metadata import requires
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.conf import settings
import os
import cv2
from .pipeline import run_pipeline, load_model_60
from .forms import ImageInfoForm
from .models import ImageInfo
import shutil
import zipfile
from io import BytesIO
from django.core.files.storage import default_storage
current_image_name = ""
# Create your views here.

def make_archive(source, destination):
        base = os.path.basename(destination)
        name = base.split('.')[0]
        format = base.split('.')[1]
        archive_from = os.path.dirname(source)
        archive_to = os.path.basename(source.strip(os.sep))
        print(source, destination, archive_from, archive_to)
        shutil.make_archive(name, format, archive_from, archive_to)
        shutil.move('%s.%s'%(name,format), destination)

def get_all_file_paths(directory):
  
    # initializing empty file paths list
    file_paths = []
  
    # crawling through directory and subdirectories
    for root, directories, files in os.walk(directory):
        for filename in files:
            # join the two strings in order to form the full filepath.
            filepath = os.path.join(root, filename)
            file_paths.append(filepath)
  
    # returning all file paths
    return file_paths  

def index(request):

    global current_image_name
    if request.method == 'POST':
        print('------------------------------------------------')
        print("Post Request!")
        image_form = ImageInfoForm(request.POST, request.FILES)

        if image_form.is_valid():
            image_name_new = image_form.cleaned_data.get("image_name")
            image_new = image_form.cleaned_data.get("image")
            obj = ImageInfo.objects.create(image_name = image_name_new, image= image_new)
            obj.save()

            current_image_name = image_name_new

            intial_path = obj.image.path
            dir_path = 'C:\\MyStuff\\PES\\Capstone_Application\\capstone_application\\media\\images\\' + image_name_new
            if not os.path.exists(dir_path):
                os.makedirs(dir_path)

            new_path = dir_path + '\\original.jpg'
            os.rename(intial_path, new_path)

            #obj.image.save(os.path.join(settings.MEDIA_ROOT, "images", image_name_new, "original.jpg"), image_new)
            model_60 = settings.MODEL_60
            if model_60 == None:
                print("NULL MODEL!!")
                image_form = ImageInfoForm()
                return render(request, 'basic_app/home.html', {'form':image_form})

            run_pipeline(new_path, dir_path, model_60)
            obj.image = 'images/'+image_name_new+'/original.jpg'
            obj.cc_image = 'images/'+image_name_new+'/cc.jpg'
            obj.save()

            #result_path = os.path.join(settings.MEDIA_ROOT, 'results', image_name_new + "_results")
            #result_path = settings.MEDIA_ROOT / 'results' / (image_name_new + "_results")
            result_path = 'C:\\MyStuff\\PES\\Capstone_Application\\capstone_application\\media\\image_results\\' + image_name_new +"_results"
            
            file_paths = get_all_file_paths(dir_path)
            print('Following files will be zipped:')
            for file in file_paths:
                    print(file)
            
            s = BytesIO()

            # The zip compressor
            zf = zipfile.ZipFile(s, "w")

            for fpath in file_paths:
                # Calculate path for file in zip
                fdir, fname = os.path.split(fpath)
                zip_path = os.path.join(fname)

                # Add file, at correct path
                zf.write(fpath, zip_path)

            # Must close zip for all contents to be written
            zf.close()

            resp = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
            # ..and correct content-disposition
            resp['Content-Disposition'] = 'attachment; filename=%s' % image_name_new


            #s.seek(0)
            # To store it we can use a InMemoryUploadedFile
            #inMemory = InMemoryUploadedFile(s, None, "my_zip_%s" % image_name_new, 'tmp/'+image_name_new, s.len, None)
            
            with default_storage.open('tmp/'+image_name_new + '.zip', 'wb') as destination:
                print(type(destination))
                destination.write(s.getbuffer())

            s.close()
            '''
            resp = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
            # ..and correct content-disposition
            resp['Content-Disposition'] = 'attachment; filename=%s' % image_name_new
            '''
            #obj.update_result('C:\\MyStuff\\PES\\Capstone_Application\\capstone_application\\media\\tmp\\' + image_name_new +'.zip')
            obj.result = 'tmp/' + image_name_new + '.zip'
            obj.save()
            return HttpResponseRedirect(reverse('basic_app:results'))
            

        #print('------------------------------------------------')
            

    else: 
        image_form = ImageInfoForm()
        return render(request, 'basic_app/home.html', {'form':image_form})

def results(request):

    global current_image_name
    print("current image: " + current_image_name)
    context_dict = {}
    imageInfo = ImageInfo.objects.filter(image_name=current_image_name)
    context_dict['image_infos'] = imageInfo

    #print("in view")
    #print(imageInfo.image_name)
    #print(imageInfo.image.url)
    #print('-----------------------')
    return render(request, 'basic_app/results.html', context=context_dict)

def info(request):
    return render(request, 'basic_app/info.html')

def about(request):
    return render(request, 'basic_app/about.html')

capstone_application/templates/basic_app/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>About</title>
</head>
<body>
    <nav class="navbar  navbar-expand-lg navbar-dark navBar">
        <a class="navbar-brand" href="{%url 'basic_app:home'%}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{%url 'basic_app:info'%}">Code</a>
              <a class="nav-item nav-link" href="{%url 'basic_app:about'%}">About</a>
            </div>
          </div>
    </nav>
    
    <h1>About</h1>
    
</body>
</html>

capstone_application/templates/basic_app/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
     <!-- CSS only -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <!-- JavaScript Bundle with Popper -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
     <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
    <nav class="navbar  navbar-expand-lg navbar-dark navBar">
      <a class="navbar-brand" href="{%url 'basic_app:home'%}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{%url 'basic_app:info'%}">Code</a>
            <a class="nav-item nav-link" href="{%url 'basic_app:about'%}">About</a>
          </div>
        </div>
    </nav>


    <div class = "container">
      <div class="centerBlock">
        <div class = "mainBlock">
          <h1 class = "headingText">Process Brahmi Script</h1>

          <form enctype="multipart/form-data" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <input class = "btn btn-primary" type="submit" name="" value="Submit">
          </form>
        </div>
    </div>
    </div>
</body>
</html>

capstone_application/templates/basic_app/info.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
    <title>Info</title>
</head>
<body>
    <nav class="navbar  navbar-expand-lg navbar-dark navBar">
        <a class="navbar-brand" href="{%url 'basic_app:home'%}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{%url 'basic_app:info'%}">Code</a>
              <a class="nav-item nav-link" href="{%url 'basic_app:about'%}">About</a>
            </div>
          </div>
    </nav>
    <h1>INFO</h1>
</body>
</html>

capstone_application/templates/basic_app/results.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>
<body>

    <nav class="navbar  navbar-expand-lg navbar-dark navBar">
        <a class="navbar-brand" href="{%url 'basic_app:home'%}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{%url 'basic_app:info'%}">Code</a>
              <a class="nav-item nav-link" href="{%url 'basic_app:about'%}">About</a>
            </div>
          </div>
    </nav>


    <div class="container">
        <div class = 'centerBlock'>
        <div class = "mainBlock">
            <div class='row'>
                <div class='col'>
                    <h1 class='headingText'>Results</h1>
                </div>
            </div>
            {% for i in image_infos %}
                <div class='row justify-content-around mt-5'>
                    <div class='col centerBlock'>
                        <div class="card" style="width: 20rem;">
                            <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap">
                            <div class="card-body cardBody">
                            <h5 class="card-title headingText">{{ i.image_name }}</h5>
                            </div>
                        </div>
                    </div>
                    <div class='col centerBlock'>
                        <div class="card" style="width: 20rem;">
                            <img class="card-img-top" src="{{ i.cc_image.url }}" alt="Card image cap">
                            <div class="card-body cardBody">
                            <h5 class="card-title headingText">{{ i.image_name }} after denoising</h5>
                            </div>
                        </div>
                    </div>
                <div>

                <div class='row mt-5'>
                    <div class='col centerBlock'>
                        <a download href="{{i.result.url}}" class="btn btn-primary">Download Predictions</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </div>

</body>
</html>